monolog:
  channels: ['email', 'events']
  handlers:
    main:
      type: stream
      path: 'php://stdout'
      level: info
    email:
      type: stream
      path: '%kernel.project_dir%/var/log/email.log'
      level: info
    events:
      type: stream
      path: '%kernel.project_dir%/var/log/events.log'
      level: info
